steps:
- name: gcr.io/cloud-builders/docker
  args: [ build, -t, gcr.io/$PROJECT_ID/AngularVMApp, . ]

images:
- gcr.io/$PROJECT_ID/AngularVMApp

options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'
