steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-angular-app', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-angular-app']

  # Step 3: Deploy the Docker image to a Kubernetes cluster or other deployment platform
  # Add your deployment steps here

options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'
