steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/angularvmapp', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/angularvmapp']

  # Step 3: SSH into Compute Engine and pull the Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh angularvminstance --project=$PROJECT_ID --zone=us-west4-b --command "docker pull gcr.io/$PROJECT_ID/angularvmapp"

   # Step 4: Run the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'angularvmapp']


options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'
